## The name of the docker network that containers will be attached to.
## If you want to proxy Packit to the host, you will need to
## arrange a proxy on this network, or use dev_mode in the web section
## below.
## Prefix for container names; we'll use {container_prefix}-(container_name)
container_prefix: packit

## Set this flag to true to prevent use of --volumes in the cli to remove
## volumes on stop
protect_data: false

## Docker org for images
repo: mrcide

## The name of the docker network that containers will be attached to.
## If you want to proxy Packit to the host, you will need to
## arrange a proxy on this network
network: packit-network

## Names of the docker volumes to use:
##
## outpack: stores the outpack metadata
## proxy_logs: stores logs from the reverse proxy (only used if proxy is given)
## (More volumes are anticipated as the tool develops)
volumes:
  outpack: outpack_volume
  proxy_logs: packit_proxy_logs

## Path to ssh key for interacting with git. You
## might use a github deploy key here. For completeness both the
## public and private parts of the keypair are listed.
ssh:
  public: VAULT:secret/ssh:public
  private: VAULT:secret/ssh:private

outpack:
  ## Initialise an outpack directory by cloning from github
  initial:
    ##  If using a private repo, then use an ssh url and provide ssh keys in the
    ## "ssh" section above.
    url: https://github.com/reside-ic/orderly3-example.git
  server:
    name: outpack_server
    tag: main
  migrate:
    name: outpack.orderly
    tag: main

packit:
  api:
    name: packit-api
    tag: main
  app:
    name: packit
    tag: main
  db:
    name: packit-db
    tag: main
    user: VAULT:secret/db/user:value
    password: VAULT:secret/db/password:value
  auth:
    enabled: true
    auth_method: github
    expiry_days: 1
    github_api_org: mrc-ide
    github_api_team: packit
    # Details of your Github OAuth app, which should be kept in the vault. The app's Authorization callback url must
    # have the same root as the packit_api_root specified below, and should be of the form
    # {PACKIT_API_ROOT}/login/oauth2/code/github
    github_client:
      id: VAULT:secret/auth/githubclient/id:value
      secret: VAULT:secret/auth/githubclient/secret:value
    jwt:
      # Secret used to generate JWT tokens - this can be any string, the secret at this key in the vault is a random
      # 32 char string, and is probably fine to re-use
      secret: VAULT:secret/auth/jwt/secret:value
    oauth2:
      redirect:
        # Root url which OAuth2 app will use to redirect back to packit api - must match OAuth2 app's registered url
        packit_api_root: "https://packit/api"
        url: "https://packit/redirect"  # Url for redirecting back to the front end after successful authentication

## If running a proxy directly, fill this section in.  Otherwise you
## are responsible for proxying the application out of the docker
## network
proxy:
  enabled: true
  ssl:
    ## This section describes how to get the certificate in.  We
    ## support two sources:
    ##
    ## 1. self signed certificates - just leave this section blank
    ##
    ## 2. certificates from strings - include the strings directly in
    ##    the keys here, or more likely use a VAULT:<path>:<key>
    ##    string to extract them from the vault.
    certificate: "VAULT:secret/cert:value"
    key: "VAULT:secret/key:value"
  hostname: localhost
  port_http: 80
  port_https: 443
  image:
    name: packit-proxy
    tag: main

vault:
  ## Address of the vault server.  This should be a string if it is
  ## present.
  addr: ~
  auth:
    ## Authentication type - must be either "token" or the name of a
    ## supported authentication method.  These seem to be poorly
    ## documented in the hvac, but include "github" for github
    ## authentication.
    ##
    ## On a vault client object, see auth.implemented_class_names for
    ## a list, which is currently
    ##
    ##     azure, github, gcp, kubernetes, ldap, mfa, okta
    method: token


## Branding configuration
## If only one of 'name' or 'logo_path' is set, both will be ignored.
brand:
  favicon_path: examplefavicon.ico # Optional custom favicon (any format). Should be in the same dir as this config file.
  logo_alt_text: My logo # Alt text for logo (optional - fallback configured in Packit)
  logo_link: https://www.google.com/ # Optional. Absolute navigation destination for clicking on logo.
  logo_path: examplelogo.webp # Custom logo image (any format). Should be in the same dir as this config file.
  name: My Packit Instance # Affects header text and page title
